#!/usr/bin/env python3
"""Export the web build and give its files content-addressed names.

    python3 tools/build_web.py [--skip-export]

Why this exists
---------------
Godot's web export always writes the same five filenames. A browser that has
cached `index.wasm` from a previous deploy has no way to know the new one
differs, and a CDN in front of it has less. The usual answer is a
`must-revalidate` header, which costs a round trip per file per load and still
fails whenever something in the chain ignores it.

So every file whose name the engine derives from the executable is renamed with
a short hash of the build:

    index.js      ->  index.<hash>.js
    index.wasm    ->  index.<hash>.wasm
    index.pck     ->  index.<hash>.pck
    index.audio.worklet.js           ->  index.<hash>.audio.worklet.js
    index.audio.position.worklet.js  ->  index.<hash>.audio.position.worklet.js

The engine finds them because it builds all five names from one string in the
page config: `"executable":"index"` becomes `"executable":"index.<hash>"`, and
the loader appends `.js`, `.wasm`, `.pck`, `.audio.worklet.js` and
`.audio.position.worklet.js` itself. Miss one of those five and the game loads
until the moment it needs the file that is not there — which for the audio
worklets is after the first frame, so it looks like an audio bug rather than a
deploy bug.

`index.html` keeps its name, because something has to be the entry point, and it
is served `no-store` so it is never the stale one.
"""
import hashlib
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "build" / "web"
PAGE = OUT / "index.html"
## Every suffix the loader derives from the executable name.
DERIVED = [".js", ".wasm", ".pck", ".audio.worklet.js", ".audio.position.worklet.js"]
## Files the page references directly and which are small enough not to matter.
STATIC = ["index.png", "index.icon.png", "index.apple-touch-icon.png"]


def export() -> None:
    # Godot will not create the target folder, and `build/` is gitignored — so
    # on a fresh checkout (which is every CI run) the directory is simply not
    # there and the export fails with "Target folder does not exist".
    OUT.mkdir(parents=True, exist_ok=True)
    print("exporting…")
    result = subprocess.run(
        ["godot", "--headless", "--export-release", "Web", str(PAGE)],
        cwd=ROOT, capture_output=True, text=True)
    errors = [line for line in result.stderr.splitlines() if line.startswith("ERROR")]
    if errors:
        print("\n".join(errors))
        sys.exit("export failed")


def clean_old() -> None:
    """Remove hashed files from previous builds, or they accumulate forever."""
    for path in OUT.glob("index.*"):
        if re.match(r"^index\.[0-9a-f]{10}\.", path.name):
            path.unlink()


def build_hash() -> str:
    digest = hashlib.sha256()
    for suffix in DERIVED:
        source = OUT / ("index" + suffix)
        if source.exists():
            digest.update(source.read_bytes())
    return digest.hexdigest()[:10]


def rename(tag: str) -> list[str]:
    written = []
    for suffix in DERIVED:
        source = OUT / ("index" + suffix)
        if not source.exists():
            # .pck is absent when the pack is embedded; the rest are not
            # optional, and a missing one is worth saying out loud.
            print("  note: %s not produced by the export" % source.name)
            continue
        target = OUT / ("index.%s%s" % (tag, suffix))
        shutil.move(source, target)
        written.append(target.name)
    return written


def rewrite_page(tag: str) -> None:
    text = PAGE.read_text()
    before = text
    text = text.replace('"executable":"index"', '"executable":"index.%s"' % tag)
    text = text.replace('src="index.js"', 'src="index.%s.js"' % tag)
    if text == before:
        sys.exit("index.html did not contain the expected references — "
                 "the export template changed and this script needs updating")
    PAGE.write_text(text)


def write_headers(tag: str) -> None:
    """Cache rules that match the naming: the page never, the rest forever."""
    lines = [
        "# Generated by tools/build_web.py — do not edit by hand.",
        "#",
        "# Cross-origin isolation is mandatory: the export uses threads, threads",
        "# need SharedArrayBuffer, and a browser only grants that to an isolated",
        "# page. Without both headers the game does not start.",
        "/*",
        "  Cross-Origin-Opener-Policy: same-origin",
        "  Cross-Origin-Embedder-Policy: require-corp",
        "",
        "# The entry point is the only file whose name does not change, so it is",
        "# the only one that must never be cached.",
        "/",
        "  Cache-Control: no-store",
        "/index.html",
        "  Cache-Control: no-store",
        "",
        "# Everything else carries the build hash in its name. A changed build is",
        "# a changed URL, so these can be kept for a year.",
        "/index.%s.*" % tag,
        "  Cache-Control: public, max-age=31536000, immutable",
        "",
    ]
    (OUT / "_headers").write_text("\n".join(lines))


def main() -> None:
    if "--skip-export" not in sys.argv:
        export()
    clean_old()
    tag = build_hash()
    written = rename(tag)
    rewrite_page(tag)
    write_headers(tag)
    total = sum(f.stat().st_size for f in OUT.glob("index.*")) / 1048576
    print("build %s — %d files, %.1f MB" % (tag, len(written), total))
    for name in written:
        print("  " + name)


if __name__ == "__main__":
    main()
